---
title: "Cleaning Chlorurs Data"
author: "Camila Vargas"
date: "12/10/2021"
output: html_document
---

This scripts cleans data provided by Peter Carlson on fish surveys for Chlorurus.

## Set up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Load packages
library(here)
library(tidyverse)
library(janitor)
library(readxl)
library(lubridate)
library(freeR)

## Sets R not to use scientific notations
options(scipen=999) 

raw_data_path <- here::here("6.raw_data/")
```


## Read data

```{r}
chlo_activity_raw <- read_csv(here::here(paste0(raw_data_path, "Chlorurus_Activity_data.csv"))) %>% 
  clean_names()


chlo_area_raw <- read_csv(here::here(paste0(raw_data_path, "Chlorurus_Area_data.csv"))) %>% 
  clean_names()


fish_meta_raw <- read_csv(here::here(paste0(raw_data_path, "Fish_Metadata.csv"))) %>% 
  clean_names()

```

- Activity look up is the metadata for the categorical variables under the Activity column.
- Fish metadata is the look-up table with all the information of each fish id

## Renaming columns
Removing unites from columns name

```{r}
chlo_activity <- chlo_activity_raw %>% 
  rename(focal_dur = focal_dur_mins,
         act_dur = act_dur_mins) %>% 
  mutate(observer = str_to_title(observer),
         date = mdy(date),
         focal_start = mdy_hm(focal_start),
         focal_end = mdy_hm(focal_end),
         act_start = mdy_hm(act_start),
         act_end = mdy_hm(act_end))

chlo_area <- chlo_area_raw %>% 
  rename(kud95_area = x95kud_area,
         kud95_feeding_area = x95kud_feeding_area)

fish_meta <- fish_meta_raw

```

## QA/QC

```{r}
## Activity
str(chlo_activity)

unique(chlo_activity$observer)
unique(chlo_activity$site)
unique(chlo_activity$species)
unique(chlo_activity$fish_id)
unique(chlo_activity$activity)
unique(chlo_activity$track_id)

complete(chlo_activity)

## Area
str(chlo_area)

unique(chlo_area$site)
unique(chlo_area$track_id)
unique(chlo_area$fish_id)
unique(chlo_area$species)

## fish metadata
str(fish_meta)

unique(fish_meta$fish_id)
unique(fish_meta$species)
unique(fish_meta$species_full_name)
unique(fish_meta$site)
unique(fish_meta$phase)

```


## Save Clean Data

```{r}
write_csv(chlo_activity, here::here("7.clean_data/Chlorurus_Activity_Palmyra_2014.csv"))

write_csv(chlo_area, here::here("7.clean_data/Chlorurus_Area_Palmyra_2014.csv"))

write_csv(fish_meta, here::here("7.clean_data/Fish_Information_Chlorurus_Data_2014.csv"))

```





